language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run report-coverage
  - greenkeeper-lockfile-upload
branches:
  only:
    - master
    - /^greenkeeper/.*$/
